  
version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
        - ..:/workspace:cached
        - ./init_db:/docker-entrypoint-initdb.d
    ports: 
      - 5432:5432
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin