  
version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
        - ..:/workspace:cached
    ports: 
      - 5432:5432
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin